#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# needed to make higher refresh rate monitor used for VRR (vsync) rather than lowest one
# set here is better than in .bashrc because menu launched apps don't see bashrc env
# export __GL_SYNC_DISPLAY_DEVICE="DP-0"

# Put setup screens bash script here. Putting this in i3 config causes weird glitch with background being distorted by picom on my higher end monitor


# launch i3wm
exec i3
